version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-sharecode
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sharecode
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: sharecode
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
